apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"blog:latest","namespace":"fiap-aso"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog\")].image"}]'
    labels:
        app: blog
        app.kubernetes.io/component: blog
        app.kubernetes.io/instance: blog
    name: blog
    namespace: fiap-aso
spec:
    replicas: 2
    selector:
        matchLabels:
            deployment: blog
    strategy: {}
    template:
        metadata:
            labels:
                deployment: blog
        spec:
            containers:
            - env:
              - name: DATABASE_URL
                value: postgresql://sampledb:sampledb@sample-database-to-blog:5432/sampledb
              image: ' '
              name: blog
              ports:
              - containerPort: 8080
                protocol: TCP
              resources: {}