apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sample-database-pv
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem