kind: Service
apiVersion: v1
metadata:
    name: sample-database-to-blog
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: sample-database-to-blog