kind: Secret
apiVersion: v1
metadata:
    name: sample-database-secret
    namespace: fiap-aso-lmsousa
data:
  database-name: c2FtcGxlZGI=
  database-password: c2FtcGxlZGI=
  database-user: c2FtcGxlZGI=